/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.PI.messages;

import PROJETO_INTEGRADOR.Senha;
import com.PI.database.DatabaseConnection;
import com.PI.database.MessageDao;
import com.PI.entidades.Contact;
import com.PI.entidades.Message;
import com.PI.verfic.TreatmentException;
import com.PI.inicial.Home;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Usuario
 */
public class AddMesForm extends javax.swing.JFrame {
    JTable sendboxTable;

    /**
     * Creates new form FormContAdd
     */
    public AddMesForm() {
        initComponents();
    }
    public void setNameField(Contact contactName) {       
        nameField.setText((contactName.getContactName()));
        nameField.setEditable(false);
    }
    private void initUpdate() {
            this.sendboxTable = SendboxForm.getSendboxTable();
            int rowSelected = sendboxTable.getSelectedRow();
            nameField.setText((String) sendboxTable.getValueAt(rowSelected, 0));
            nameField.setEditable(false);
            messageArea.setText((String) sendboxTable.getValueAt(rowSelected, 1));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        labelTel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        scrollMessage = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        cancelMsgBtn = new javax.swing.JButton();
        cleanMsgBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enviar mensagem");
        setBackground(new java.awt.Color(204, 255, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelNome.setBackground(new java.awt.Color(204, 255, 204));
        labelNome.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelNome.setLabelFor(nameField);
        labelNome.setText("Contato:");

        labelTel.setBackground(new java.awt.Color(204, 255, 204));
        labelTel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelTel.setLabelFor(messageArea);
        labelTel.setText("Mensagem:");

        nameField.setColumns(15);
        nameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        saveBtn.setText("Enviar");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        messageArea.setColumns(20);
        messageArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        messageArea.setLineWrap(true);
        messageArea.setRows(7);
        messageArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        messageArea.setMaximumSize(new java.awt.Dimension(800, 800));
        scrollMessage.setViewportView(messageArea);

        cancelMsgBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cancelMsgBtn.setText("Cancelar");
        cancelMsgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMsgBtnActionPerformed(evt);
            }
        });

        cleanMsgBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cleanMsgBtn.setText("Limpar");
        cleanMsgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanMsgBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addGap(18, 18, 18)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cleanMsgBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelMsgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollMessage))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cleanMsgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelMsgBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            validateRequiredFields();
            DatabaseConnection databaseConnection = new DatabaseConnection(
            "root", Senha.getPass(), "manager_messages", "localhost", 3306);
            MessageDao messageDao = new MessageDao(databaseConnection); 
            
            Message message = new Message(messageArea.getText());
            if (this.getTitle().startsWith("Ed")) { //update               
                message.setId(Home.getMsgIdForUpdate(sendboxTable));
                messageDao.update(message);
            } else { //save     
                Contact contId = new Contact(Home.getContIdForUpdate());
                message.setContId(contId);
                messageDao.save(message);
            }    
            
            JOptionPane.showMessageDialog(rootPane, "Mensagem enviada com sucesso!", 
                "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);  
            databaseConnection.getConnection().close();  
        } catch (TreatmentException treatmentException) {
        JOptionPane.showMessageDialog(rootPane, treatmentException.getMessage(),
            "Campos inválidos", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            switch (ex.getErrorCode()) {
                case 1406 -> JOptionPane.showMessageDialog(rootPane, 
                            "Tamanho máximo de 255 caracteres excedido",
                            "Erro", JOptionPane.ERROR_MESSAGE);
                default -> JOptionPane.showMessageDialog(rootPane,           
                        "Erro inesperado aconteceu! " + ex.getErrorCode() + ex.getMessage(),
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelMsgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMsgBtnActionPerformed
            this.setVisible(false);
    }//GEN-LAST:event_cancelMsgBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (this.getTitle().startsWith("Ed")) {
            initUpdate();
        }
    }//GEN-LAST:event_formWindowOpened

    private void cleanMsgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanMsgBtnActionPerformed
        messageArea.setText("");
    }//GEN-LAST:event_cleanMsgBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddMesForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelMsgBtn;
    private javax.swing.JButton cleanMsgBtn;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTel;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JScrollPane scrollMessage;
    // End of variables declaration//GEN-END:variables
    private void validateRequiredFields() throws TreatmentException {
        if ((nameField.getText().isBlank())||(messageArea.getText().isBlank())) {           
            throw new TreatmentException("Todos os campos são obrigatórios!");
        }    
    }   
}

